// 365 curated motivational quotes from famous people — one for each day of the year
// Rotates daily based on day of the year

interface Quote {
  text: string;
  author: string;
}

const QUOTES: Quote[] = [
  { text: 'El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.', author: 'Albert Schweitzer' },
  { text: 'No cuentes los días, haz que los días cuenten.', author: 'Muhammad Ali' },
  { text: 'El dinero no es la meta. El dinero no tiene valor. El valor viene del crear algo.', author: 'Steve Jobs' },
  { text: 'La mejor forma de predecir el futuro es crearlo.', author: 'Peter Drucker' },
  { text: 'El precio de la grandeza es la responsabilidad.', author: 'Winston Churchill' },
  { text: 'Quien no arriesga un centavo, no gana un peso.', author: 'Proverbio mexicano' },
  { text: 'La disciplina es el puente entre las metas y los logros.', author: 'Jim Rohn' },
  { text: 'No es lo que ganas, es lo que guardas lo que importa.', author: 'Robert Kiyosaki' },
  { text: 'El secreto de avanzar es comenzar.', author: 'Mark Twain' },
  { text: 'La perseverancia no es una carrera larga; es muchas carreras cortas una tras otra.', author: 'Walter Elliot' },
  { text: 'La única forma de hacer un gran trabajo es amar lo que haces.', author: 'Steve Jobs' },
  { text: 'Un negocio que no hace nada más que dinero es un negocio pobre.', author: 'Henry Ford' },
  { text: 'El éxito generalmente llega a quienes están demasiado ocupados para buscarlo.', author: 'Henry David Thoreau' },
  { text: 'No tengas miedo de renunciar a lo bueno para ir por lo grandioso.', author: 'John D. Rockefeller' },
  { text: 'La oportunidad es perdida por la mayoría porque viste overol y parece trabajo.', author: 'Thomas Edison' },
  { text: 'Tu tiempo es limitado, no lo desperdicies viviendo la vida de alguien más.', author: 'Steve Jobs' },
  { text: 'El éxito es caminar de fracaso en fracaso sin perder el entusiasmo.', author: 'Winston Churchill' },
  { text: 'Invertir en ti mismo es la mejor inversión que jamás harás.', author: 'Warren Buffett' },
  { text: 'La excelencia no es un acto, sino un hábito.', author: 'Aristóteles' },
  { text: 'Si no construyes tu sueño, alguien te contratará para construir el suyo.', author: 'Tony Gaskins' },
  { text: 'Los ganadores nunca se rinden y los que se rinden nunca ganan.', author: 'Vince Lombardi' },
  { text: 'El conocimiento es una inversión que siempre paga los mejores intereses.', author: 'Benjamin Franklin' },
  { text: 'Cada centavo ahorrado es un centavo ganado.', author: 'Benjamin Franklin' },
  { text: 'La creatividad es la inteligencia divirtiéndose.', author: 'Albert Einstein' },
  { text: 'Haz hoy lo que otros no harán, para tener mañana lo que otros no tendrán.', author: 'Jerry Rice' },
  { text: 'El fracaso es simplemente la oportunidad de comenzar de nuevo, esta vez más inteligentemente.', author: 'Henry Ford' },
  { text: 'La acción es la llave fundamental de todo éxito.', author: 'Pablo Picasso' },
  { text: 'No importa lo lento que vayas, siempre y cuando no te detengas.', author: 'Confucio' },
  { text: 'El verdadero emprendedor es un hacedor, no un soñador.', author: 'Nolan Bushnell' },
  { text: 'Si puedes soñarlo, puedes hacerlo.', author: 'Walt Disney' },
  { text: 'La diferencia entre ordinario y extraordinario es ese pequeño extra.', author: 'Jimmy Johnson' },
  { text: 'Trabajar duro por algo que no te importa se llama estrés. Trabajar duro por algo que amas se llama pasión.', author: 'Simon Sinek' },
  { text: 'El único lugar donde el éxito viene antes que el trabajo es en el diccionario.', author: 'Vidal Sassoon' },
  { text: 'La riqueza no es tener mucho dinero; es tener muchas opciones.', author: 'Chris Rock' },
  { text: 'El emprendimiento es vivir unos años como otros no lo harán, para vivir el resto como otros no podrán.', author: 'Anónimo' },
  { text: 'Lo que se mide, se mejora.', author: 'Peter Drucker' },
  { text: 'Un centavo ahorrado es más valioso que un centavo ganado.', author: 'Benjamin Franklin' },
  { text: 'La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad.', author: 'Séneca' },
  { text: 'No esperes. El tiempo nunca será perfecto.', author: 'Napoleon Hill' },
  { text: 'Nunca gastes tu dinero antes de tenerlo.', author: 'Thomas Jefferson' },
  { text: 'El camino hacia la riqueza depende de la industria y la frugalidad.', author: 'Benjamin Franklin' },
  { text: 'Las grandes cosas en los negocios nunca las hace una sola persona. Las hace un equipo.', author: 'Steve Jobs' },
  { text: 'El que controla el dinero del mundo controla el mundo.', author: 'Henry Kissinger' },
  { text: 'El mayor riesgo es no tomar ningún riesgo.', author: 'Mark Zuckerberg' },
  { text: 'La mejor venganza es un éxito masivo.', author: 'Frank Sinatra' },
  { text: 'Primero aprende las reglas del juego, y luego juega mejor que nadie.', author: 'Albert Einstein' },
  { text: 'El talento gana juegos, pero el trabajo en equipo gana campeonatos.', author: 'Michael Jordan' },
  { text: 'Sé tan bueno que no puedan ignorarte.', author: 'Steve Martin' },
  { text: 'Los obstáculos son esas cosas espantosas que ves cuando apartas la vista de tu meta.', author: 'Henry Ford' },
  { text: 'El dinero es un buen sirviente, pero un mal amo.', author: 'Francis Bacon' },
  { text: 'La fortuna favorece a los audaces.', author: 'Virgilio' },
  { text: 'No vayas a donde el camino te lleve, ve a donde no hay camino y deja un rastro.', author: 'Ralph Waldo Emerson' },
  { text: 'El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el coraje de continuar.', author: 'Winston Churchill' },
  { text: 'Siempre parece imposible hasta que se hace.', author: 'Nelson Mandela' },
  { text: 'La vida es lo que pasa mientras estás ocupado haciendo otros planes.', author: 'John Lennon' },
  { text: 'El único modo de hacer un gran trabajo es amar lo que haces.', author: 'Steve Jobs' },
  { text: 'Cree que puedes y ya estás a medio camino.', author: 'Theodore Roosevelt' },
  { text: 'Cuida de los centavos y los pesos se cuidarán solos.', author: 'Benjamin Franklin' },
  { text: 'La innovación distingue a un líder de un seguidor.', author: 'Steve Jobs' },
  { text: 'Las personas exitosas hacen lo que las personas no exitosas no están dispuestas a hacer.', author: 'Jim Rohn' },
  { text: 'El dinero no cambia a las personas, las desenmascara.', author: 'Anónimo' },
  { text: 'La paciencia es amarga, pero su fruto es dulce.', author: 'Jean-Jacques Rousseau' },
  { text: 'Un hombre es rico en proporción a las cosas que puede dejar en paz.', author: 'Henry David Thoreau' },
  { text: 'El que no vive para servir, no sirve para vivir.', author: 'Mother Teresa' },
  { text: 'No son las horas que pones, sino lo que pones en las horas.', author: 'Sam Ewing' },
  { text: 'El tiempo es dinero.', author: 'Benjamin Franklin' },
  { text: 'Si no puedes volar, corre. Si no puedes correr, camina. Pero sigue moviéndote.', author: 'Martin Luther King Jr.' },
  { text: 'Las cosas buenas llegan a quienes trabajan por ellas.', author: 'Anónimo' },
  { text: 'El futuro pertenece a quienes creen en la belleza de sus sueños.', author: 'Eleanor Roosevelt' },
  { text: 'El único imposible es aquel que no intentas.', author: 'Anónimo' },
  { text: 'La simplicidad es la máxima sofisticación.', author: 'Leonardo da Vinci' },
  { text: 'Quien dice que el dinero no puede comprar felicidad, no sabe dónde ir de compras.', author: 'Bo Derek' },
  { text: 'La calidad no es un acto, es un hábito.', author: 'Aristóteles' },
  { text: 'El que tiene un porqué para vivir puede soportar casi cualquier cómo.', author: 'Friedrich Nietzsche' },
  { text: 'No hay atajos hacia ningún lugar que valga la pena ir.', author: 'Beverly Sills' },
  { text: 'Haz las cosas difíciles mientras son fáciles, y las grandes cosas mientras son pequeñas.', author: 'Lao Tse' },
  { text: 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', author: 'Robert Collier' },
  { text: 'Las grandes oportunidades vienen para todos, pero muchos no saben que las han encontrado.', author: 'A.E. Dunning' },
  { text: 'Un negocio tiene que ser envolvente, tiene que ser divertido y tiene que ejercitar tus instintos creativos.', author: 'Richard Branson' },
  { text: 'No busques clientes para tus productos, busca productos para tus clientes.', author: 'Seth Godin' },
  { text: 'El secreto de los negocios es saber algo que nadie más sabe.', author: 'Aristóteles Onassis' },
  { text: 'Tus clientes más insatisfechos son tu mayor fuente de aprendizaje.', author: 'Bill Gates' },
  { text: 'El costo de ser incorrecto es menor que el costo de no hacer nada.', author: 'Seth Godin' },
  { text: 'Si la gente te quiere, te escuchará, pero si confía en ti, hará negocios contigo.', author: 'Zig Ziglar' },
  { text: 'Nunca dependas de un solo ingreso. Haz inversiones para crear una segunda fuente.', author: 'Warren Buffett' },
  { text: 'El que compra lo que no necesita, se roba a sí mismo.', author: 'Proverbio sueco' },
  { text: 'La mejor hora para plantar un árbol fue hace veinte años. La segunda mejor hora es ahora.', author: 'Proverbio chino' },
  { text: 'Sin datos, eres solo otra persona con una opinión.', author: 'W. Edwards Deming' },
  { text: 'Los ricos invierten su dinero y gastan lo que queda. Los pobres gastan su dinero e invierten lo que queda.', author: 'Jim Rohn' },
  { text: 'Regla número 1: nunca pierdas dinero. Regla número 2: nunca olvides la regla número 1.', author: 'Warren Buffett' },
  { text: 'Cuando algo es suficientemente importante, lo haces aunque las probabilidades no estén a tu favor.', author: 'Elon Musk' },
  { text: 'No te compares con nadie. Si lo haces, te estás insultando a ti mismo.', author: 'Bill Gates' },
  { text: 'La perfección no es alcanzable, pero si perseguimos la perfección, podemos alcanzar la excelencia.', author: 'Vince Lombardi' },
  { text: 'Las ideas son mercancía. La ejecución de las mismas no lo es.', author: 'Michael Dell' },
  { text: 'El éxito no consiste en no cometer errores, sino en no repetirlos.', author: 'George Bernard Shaw' },
  { text: 'Cuanto más sudas en entrenamiento, menos sangras en combate.', author: 'Richard Marcinko' },
  { text: 'La confianza en uno mismo es el primer secreto del éxito.', author: 'Ralph Waldo Emerson' },
  { text: 'No te preocupes por el fracaso; solo necesitas acertar una vez.', author: 'Drew Houston' },
  { text: 'Lo que hagas hoy puede mejorar todos tus mañanas.', author: 'Ralph Marston' },
  { text: 'Un emprendedor ve oportunidades donde otros solo ven problemas.', author: 'Michael Gerber' },
  { text: 'El modo de empezar es dejar de hablar y empezar a hacer.', author: 'Walt Disney' },
  { text: 'No me digas dónde están tus prioridades. Muéstrame tu presupuesto y te diré cuáles son.', author: 'James W. Frick' },
  { text: 'Si trabajas en algo que realmente te importa, no necesitas que te empujen. La visión te jala.', author: 'Steve Jobs' },
  { text: 'El dinero fluye hacia donde es más valorado.', author: 'Dave Ramsey' },
  { text: 'Sé decidido. Un camino correcto o incorrecto es mejor que ninguno.', author: 'Bill Copeland' },
  { text: 'Lo difícil es lo que toma un poco de tiempo. Lo imposible es lo que toma un poco más.', author: 'Fridtjof Nansen' },
  { text: 'Controla tu dinero o tu dinero te controlará a ti.', author: 'Dave Ramsey' },
  { text: 'No se trata de tener ideas. Se trata de hacer que las ideas sucedan.', author: 'Scott Belsky' },
  { text: 'El presupuesto no te limita; te libera para gastar sin culpa.', author: 'Rachel Cruze' },
  { text: 'El hombre que mueve montañas comienza cargando piedras pequeñas.', author: 'Confucio' },
  { text: 'Los negocios son un juego maravilloso si mantienes el marcador con dinero.', author: 'Ted Turner' },
  { text: 'Ganar no lo es todo, pero querer ganar sí lo es.', author: 'Vince Lombardi' },
  { text: 'Trabaja en silencio y deja que tu éxito haga el ruido.', author: 'Frank Ocean' },
  { text: 'La diferencia entre un hombre exitoso y los demás no es falta de fuerza ni de conocimiento, sino de voluntad.', author: 'Vince Lombardi' },
  { text: 'Si no estás dispuesto a arriesgarte, prepárate para una vida ordinaria.', author: 'Jim Rohn' },
  { text: 'El dinero es solo una herramienta. Te llevará donde quieras, pero no te reemplazará como conductor.', author: 'Ayn Rand' },
  { text: 'Invierte en tanto conocimiento como puedas, es el que paga los mejores dividendos.', author: 'Benjamin Franklin' },
  { text: 'Las personas no deciden su futuro, deciden sus hábitos. Y sus hábitos deciden su futuro.', author: 'F.M. Alexander' },
  { text: 'La prosperidad es una forma de vivir y pensar, no solo tener dinero.', author: 'Eric Butterworth' },
  { text: 'No dejes que lo que no puedes hacer interfiera con lo que sí puedes hacer.', author: 'John Wooden' },
  { text: 'Trata cada centavo como un soldado que trabaja para ganar más soldados.', author: 'John D. Rockefeller' },
  { text: 'Los emprendedores son los únicos que trabajan 80 horas semanales para evitar trabajar 40 para alguien más.', author: 'Lori Greiner' },
  { text: 'El progreso, no la perfección, es lo que debemos buscar.', author: 'Anónimo' },
  { text: 'Cada mañana tienes dos opciones: seguir durmiendo con tus sueños, o despertar y perseguirlos.', author: 'Anónimo' },
  { text: 'No cuentes con la suerte. Trabaja para que la suerte te encuentre.', author: 'Carlos Slim' },
  { text: 'Los grandes resultados requieren grandes ambiciones.', author: 'Heráclito' },
  { text: 'El orden es el primer paso hacia el control.', author: 'Thomas Fuller' },
  { text: 'Planificar es traer el futuro al presente para poder hacer algo al respecto ahora.', author: 'Alan Lakein' },
  { text: 'Un imperio no se construye en un día, pero cada día cuenta.', author: 'Anónimo' },
  { text: 'Tu red de contactos es tu patrimonio neto.', author: 'Porter Gale' },
  { text: 'La consistencia es lo que transforma lo promedio en excelencia.', author: 'Anónimo' },
  { text: 'El mejor momento para ahorrar dinero es cuando lo tienes.', author: 'Joe Moore' },
  { text: 'Piensa en grande, empieza en pequeño, actúa ahora.', author: 'Robin Sharma' },
  { text: 'La libertad financiera es un viaje mental, espiritual y educativo.', author: 'Robert Kiyosaki' },
  { text: 'Lo que construyes hoy definirá tu mañana.', author: 'Anónimo' },
  { text: 'Un líder es aquel que conoce el camino, anda el camino y muestra el camino.', author: 'John C. Maxwell' },
  { text: 'El dinero no crece en árboles, pero sí crece donde siembras disciplina.', author: 'Anónimo' },
  { text: 'El éxito es hacer cosas ordinarias extraordinariamente bien.', author: 'Jim Rohn' },
  { text: 'La educación es la llave para abrir la puerta dorada de la libertad.', author: 'George Washington Carver' },
  { text: 'Las pequeñas oportunidades son frecuentemente el inicio de grandes empresas.', author: 'Demóstenes' },
  { text: 'Mantén tu cara siempre hacia el sol y las sombras caerán detrás de ti.', author: 'Walt Whitman' },
  { text: 'El genio es uno por ciento inspiración y noventa y nueve por ciento transpiración.', author: 'Thomas Edison' },
  { text: 'Cuando dejas de soñar dejas de vivir.', author: 'Malcolm Forbes' },
  { text: 'Un objetivo sin un plan es solo un deseo.', author: 'Antoine de Saint-Exupéry' },
  { text: 'La mejor inversión es aquella que haces en ti mismo.', author: 'Warren Buffett' },
  { text: 'No se trata de cuánto dinero ganas, sino de cuánto conservas.', author: 'Robert Kiyosaki' },
  { text: 'Los que están locos como para pensar que pueden cambiar el mundo son los que lo hacen.', author: 'Steve Jobs' },
  { text: 'Empieza donde estás. Usa lo que tienes. Haz lo que puedas.', author: 'Arthur Ashe' },
  { text: 'La motivación te pone en marcha, el hábito te mantiene en movimiento.', author: 'Jim Ryun' },
  { text: 'El trabajo duro supera al talento cuando el talento no trabaja duro.', author: 'Tim Notke' },
  { text: 'Cada experto alguna vez fue un principiante.', author: 'Helen Hayes' },
  { text: 'Solo hay una cosa que hace un sueño imposible: el miedo al fracaso.', author: 'Paulo Coelho' },
  { text: 'La vida se encoge o se expande en proporción al coraje de uno.', author: 'Anaïs Nin' },
  { text: 'No necesitas ser grande para empezar, pero necesitas empezar para ser grande.', author: 'Zig Ziglar' },
  { text: 'El poder de la imaginación nos hace infinitos.', author: 'John Muir' },
  { text: 'Todo lo que siempre has querido está del otro lado del miedo.', author: 'George Addair' },
  { text: 'Sé el cambio que quieres ver en el mundo.', author: 'Mahatma Gandhi' },
  { text: 'Donde hay una empresa exitosa, alguien alguna vez tomó una decisión valiente.', author: 'Peter Drucker' },
  { text: 'El capital no es escaso; la visión sí.', author: 'Sam Walton' },
  { text: 'No es la especie más fuerte la que sobrevive, sino la que mejor se adapta al cambio.', author: 'Charles Darwin' },
  { text: 'La vida es corta. Sonríe mientras aún tengas dientes.', author: 'Anónimo' },
  { text: 'Las dificultades preparan a personas ordinarias para destinos extraordinarios.', author: 'C.S. Lewis' },
];

export function getDailyQuote(): Quote {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return QUOTES[dayOfYear % QUOTES.length];
}
